#!/usr/bin/env bash
# -*- mode: sh; -*-
########################################################################
#  GitHub Actions CI script
########################################################################
#
# To run locally:
#
#   docker run --rm -v "$(pwd)/build-github:/build-github:ro" debian:trixie \
#      -e GITHUB_REF_NAME=$BRANCH \
#      bash /build-github https://github.com/rlauer6/Amazon-S3-Lite.git
#
#  --or--
#
#  make build-ci
#
########################################################################

########################################################################
function install_deps {
########################################################################
# Regenerate cpanfile for CI - includes build-requires and test-requires
# in addition to runtime requires. The committed cpanfile only contains
# runtime dependencies for consumer installs.

    all_requires=$(mktemp)

    trap 'rm -f "$all_requires"' EXIT

    test -e requires && cat requires >> $all_requires
    test -e build-requires && cat build-requires >> $all_requires
    test -e test-requires && cat test-requires >> $all_requires

    perl -ne 'chomp;($m,$v)=split /(?:[@]|\s+)/,$_,2; $v //= q{}; $m=~s/^\+//; $v = $v eq q{0} ? q{} : $v; print qq{requires "$m", "$v";\n};' \
         $all_requires | sort -u  >cpanfile

    cpanm --installdeps .
}

########################################################################
# main script starts here
########################################################################

REPO="$1"

set -euo pipefail
set -x

########################################################################
# libexpat, libssl, libzip required for building certain CPAN
# distributions like XML::Twig, Net::SSLeay, etc.
#
# Add you any additional libraries you need to this list:
########################################################################
LIB_DEPS=(libexpat-dev libssl-dev libzip-dev)

########################################################################
# Uncomment the next line if you are using a mirror.
#-----------------------------------------------------------------------
# # `cpanm` has a bug in HTTP::Tinyish::Curl that does not cleanup the
# 02packages.details.txt.gz file when curl fails to find it.  So far
# the author has been unwilling to fix the bug or accept a PR.  cpanm
# will use LWP instead if it is installed, so we'll use the workaround
# for now.
########################################################################
EXTRA_DEPS=(LWP LWP::Protocol::https)

########################################################################
# Uncomment this line to enable perltidy
########################################################################
EXTRA_DEPS+=(Perl::Tidy)

########################################################################
# Uncomment this line to enable perlcritic
########################################################################
EXTRA_DEPS+=(Perl::Critic)

apt-get update && apt-get install -y \
  git \
  gcc \
  make \
  perl \
  curl \
  ca-certificates \
  "${LIB_DEPS[@]}"

curl -L https://cpanmin.us | perl - App::cpanminus 

########################################################################
# Add your mirror to the list to use a DarkPAN mirror
########################################################################
MIRRORS=(--mirror https://cpan.openbedrock.net/orepan2 --mirror https://cpan.metacpan.org)

cpanm -n -v "${EXTRA_DEPS[@]}"

export PERL_CPANM_OPT="-n -v ${MIRRORS[@]}"

if [[ -n "$REPO" ]]; then
    git clone $REPO

    GITHUB_WORKSPACE=$(basename $REPO .git)
    cd $GITHUB_WORKSPACE
fi

if [[ -n "${GITHUB_REF_NAME:-}" ]]; then
    git checkout "$GITHUB_REF_NAME"
fi

install_deps

########################################################################
# Note that we deliberately do the robust build:
# LINT=on, SCAN=on, PERLCRITIC=on, PERLTIDY=on
#-----------------------------------------------------------------------
# If your build does not work with these on, try turning them
# off by uncommenting the lines below.
#-----------------------------------------------------------------------
# LINT=off
# SYNTAX_CHECKING=off
# PERLTIDYRC=""
# PERLCRITICRC=""
# SCAN=off
########################################################################

########################################################################
# Uncomment these to increase verbosity level of the build
########################################################################
# make-cpan-dist debug mode
#-----------------------------------------------------------------------
# DEBUG=1
########################################################################

########################################################################
# make-cpan-dist.pl log level
#-----------------------------------------------------------------------
# LOG_LEVEL=trace
########################################################################

########################################################################
# Full output of make steps
#-----------------------------------------------------------------------
# export NO_ECHO=""
########################################################################

make
