#!/bin/bash
# -*- mode: sh; -*-
#  build script for GitHub actions

REPO="$1"

set -euo pipefail
set -x

apt-get update && apt-get install -y \
  git gcc make automake autoconf perl curl ca-certificates

curl -L https://cpanmin.us | perl - App::cpanminus 

git clone $REPO
WORKDIR=$(basename $REPO .git)
cd $WORKDIR

for a in $(cat build-requires); do
    cpanm -n -v $a;
done

./bootstrap && ./configure
DEBUG=1 make
cd cpan && make cpan

